ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
SELECT USERNAME FROM DBA_USERS;
--kupid 계정 설정
CREATE USER kupid IDENTIFIED BY lovekupid DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO kupid;
-- 계정 삭제 (해당 계정이 생성한 모든 데이터까지)
--DROP USER kupid CASCADE;